'use client'

import { useMemo, useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, Bell, Boxes, ChevronDown, CircleHelp, Cpu, Database, Flame, Gauge, Layers3, Menu, Network, Play, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Workflow, X } from 'lucide-react'

type Log = { title: string; prompt: string; tokens: number; time: string; strategy: string; status: string }

const seedLogs: Log[] = [
  { title: 'Aviator Telemetry Sync', prompt: 'Build a low-overhead real-time telemetry chart canvas update engine', tokens: 1420, time: '2m ago', strategy: 'Parallel', status: 'success' },
  { title: 'Inventory Microservice', prompt: 'Build a microservice that tracks inventory across 5 warehouses', tokens: 890, time: '18m ago', strategy: 'Sequential', status: 'success' },
  { title: 'Atlas Revenue Watch', prompt: 'Create an alerting loop for multi-region revenue anomalies', tokens: 1128, time: '41m ago', strategy: 'Parallel', status: 'success' },
]

const navItems = [{ label: 'Overview', icon: Activity }, { label: 'Prompt Lab', icon: Sparkles }, { label: 'Run History', icon: Terminal }, { label: 'Crew Library', icon: Boxes }]

export default function Home() {
  const [blueprint, setBlueprint] = useState('Build a fault-tolerant event pipeline that monitors agent latency and reroutes failing tasks automatically.')
  const [strategy, setStrategy] = useState('Parallel')
  const [concurrency, setConcurrency] = useState(8)
  const [running, setRunning] = useState(false)
  const [logs, setLogs] = useState(seedLogs)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [query, setQuery] = useState('')

  const filteredLogs = useMemo(() => logs.filter((log) => `${log.title} ${log.prompt}`.toLowerCase().includes(query.toLowerCase())), [logs, query])

  function igniteCrew() {
    setRunning(true)
    window.setTimeout(() => {
      setLogs((items) => [{ title: blueprint.slice(0, 28) + '…', prompt: blueprint, tokens: 764, time: 'now', strategy, status: 'success' }, ...items])
      setRunning(false)
    }, 1200)
  }

  return <main className="min-h-screen bg-transparent">
    <div className="flex min-h-screen">
      <aside className={`fixed inset-y-0 left-0 z-20 w-64 border-r border-[var(--line)] bg-[#0b0e14]/95 px-5 py-6 backdrop-blur-xl transition-transform lg:static lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-[var(--orange)] text-[#160c05]"><Flame /></div><div><div className="font-semibold tracking-[.16em]">EMBERSPACK</div><div className="mono text-[10px] text-[var(--muted)]">ORCHESTRATION OS</div></div></div><button onClick={() => setMobileOpen(false)} className="text-[var(--muted)] lg:hidden"><X /></button></div>
        <div className="mt-12 flex flex-col gap-2">{navItems.map(({ label, icon: Icon }, index) => <button key={label} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${index === 0 ? 'bg-[#182331] text-[var(--cyan)]' : 'text-[var(--muted)] hover:bg-[var(--panel-2)] hover:text-white'}`}><Icon data-icon="inline-start" />{label}{index === 1 && <span className="mono ml-auto text-[10px] text-[var(--orange)]">BETA</span>}</button>)}</div>
        <div className="mt-10 border-t border-[var(--line)] pt-6"><div className="mono mb-3 text-[10px] uppercase tracking-[.2em] text-[var(--muted)]">Workspace</div><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[var(--muted)] hover:bg-[var(--panel-2)]"><Settings2 />Settings</button><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[var(--muted)] hover:bg-[var(--panel-2)]"><CircleHelp />Documentation</button></div>
        <div className="absolute bottom-6 left-5 right-5 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="flex items-center gap-2 text-xs text-[var(--green)]"><span className="size-2 rounded-full bg-[var(--green)]" />All systems operational</div><div className="mono mt-2 text-[10px] text-[var(--muted)]">v0.8.4 / region iad1</div></div>
      </aside>
      {mobileOpen && <button aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-10 bg-black/60 lg:hidden" />}
      <section className="min-w-0 flex-1">
        <header className="flex h-20 items-center justify-between border-b border-[var(--line)] px-5 sm:px-8"><button onClick={() => setMobileOpen(true)} className="text-[var(--muted)] lg:hidden"><Menu /></button><div className="hidden items-center gap-3 lg:flex"><span className="mono text-xs text-[var(--muted)]">CONTROL PLANE</span><span className="text-[var(--line)]">/</span><span className="text-sm">Overview</span></div><div className="ml-auto flex items-center gap-4"><div className="hidden items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-xs sm:flex"><Database className="text-[var(--cyan)]" /> Neon connected <span className="size-1.5 rounded-full bg-[var(--green)]" /></div><button className="relative text-[var(--muted)]"><Bell /><span className="absolute -right-1 -top-1 size-2 rounded-full bg-[var(--orange)]" /></button><div className="flex size-9 items-center justify-center rounded-full border border-[var(--line)] bg-[#273245] text-xs font-semibold">NX</div></div></header>
        <div className="mx-auto max-w-[1500px] p-5 sm:p-8"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mono mb-3 text-xs uppercase tracking-[.18em] text-[var(--cyan)]">/ workspace overview</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Good morning, Alex.</h1><p className="mt-2 max-w-xl text-sm text-[var(--muted)]">Your crews are warmed up and ready to turn raw intent into production-grade execution plans.</p></div><button onClick={igniteCrew} className="flex items-center justify-center gap-2 rounded-lg bg-[var(--orange)] px-5 py-3 text-sm font-semibold text-[#1a0d05] transition hover:brightness-110"><Play data-icon="inline-start" /> {running ? 'Igniting…' : 'Ignite a Crew'} <ArrowUpRight data-icon="inline-end" /></button></div>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Active Crews','12','+20.1%','Layers3'],['Prompts Optimized','1,284','+14.8%','Sparkles'],['Avg. Token Savings','32.4%','+8.2%','Gauge'],['Success Rate','98.6%','+2.4%','ShieldCheck']].map(([label, value, delta, icon]) => { const Icon = ({Layers3, Sparkles, Gauge, ShieldCheck} as any)[icon]; return <div key={label} className="glow rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex items-center justify-between"><span className="mono text-[10px] uppercase tracking-[.16em] text-[var(--muted)]">{label}</span><Icon className="text-[var(--cyan)]" /></div><div className="mt-5 flex items-end justify-between"><span className="text-3xl font-semibold">{value}</span><span className="mono text-xs text-[var(--green)]">{delta}</span></div></div> })}</div>
          <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)]"><div className="rounded-xl border border-[var(--line)] bg-[var(--panel)]"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-4"><div><div className="font-semibold">Prompt Orchestration</div><div className="mono mt-1 text-[10px] text-[var(--muted)]">DEFINE BLUEPRINT / SELECT STRATEGY / DEPLOY</div></div><SlidersHorizontal className="text-[var(--muted)]" /></div><div className="p-5"><label htmlFor="blueprint" className="mono mb-2 block text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Raw blueprint</label><textarea id="blueprint" value={blueprint} onChange={(e) => setBlueprint(e.target.value)} className="min-h-32 w-full resize-y rounded-lg border border-[var(--line)] bg-[#0b0e14] p-4 text-sm leading-6 text-white outline-none transition focus:border-[var(--cyan)]" /><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="strategy" className="mono mb-2 block text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Execution strategy</label><div className="relative"><select id="strategy" value={strategy} onChange={(e) => setStrategy(e.target.value)} className="w-full appearance-none rounded-lg border border-[var(--line)] bg-[#0b0e14] px-3 py-3 text-sm outline-none focus:border-[var(--cyan)]"><option>Parallel</option><option>Sequential</option><option>Hierarchical</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 text-[var(--muted)]" /></div></div><div><div className="mb-2 flex justify-between"><label htmlFor="concurrency" className="mono text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Max concurrency</label><span className="mono text-xs text-[var(--cyan)]">{concurrency} threads</span></div><input id="concurrency" type="range" min="1" max="16" value={concurrency} onChange={(e) => setConcurrency(Number(e.target.value))} className="mt-3 w-full accent-[var(--cyan)]" /></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--line)] pt-5"><div className="flex items-center gap-2 text-xs text-[var(--muted)]"><Cpu className="text-[var(--orange)]" /> 4 specialist agents attached</div><button onClick={igniteCrew} disabled={running || !blueprint.trim()} className="rounded-lg border border-[var(--cyan)] bg-[var(--cyan)] px-5 py-2.5 text-sm font-semibold text-[#071218] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50">{running ? 'Compiling blueprint…' : 'Compile & Run'}</button></div></div></div>
          <div className="rounded-xl border border-[var(--line)] bg-[var(--panel)]"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-4"><div><div className="font-semibold">Live Crew Status</div><div className="mono mt-1 text-[10px] text-[var(--green)]">● 4 AGENTS ACTIVE</div></div><button className="text-[var(--muted)]"><Network /></button></div><div className="flex flex-col gap-4 p-5">{[['Orchestrator','Decomposing blueprint','92%','text-[var(--cyan)]'],['Researcher','Gathering context','67%','text-[var(--orange)]'],['Architect','Structuring output','41%','text-purple-300'],['Validator','Awaiting handoff','12%','text-[var(--muted)]']].map(([name, task, progress, color], i) => <div key={name} className="rounded-lg border border-[var(--line)] bg-[#0b0e14] p-4"><div className="flex items-center gap-3"><div className={`flex size-8 items-center justify-center rounded-full bg-[#1e293b] ${color}`}><span className="mono text-xs">0{i + 1}</span></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2 text-sm"><span>{name}</span><span className="mono text-[10px] text-[var(--muted)]">{progress}</span></div><div className="mt-1 truncate text-xs text-[var(--muted)]">{task}</div></div></div><div className="mt-3 h-1 rounded-full bg-[#202638]"><div className={`h-full rounded-full ${i === 0 ? 'bg-[var(--cyan)]' : i === 1 ? 'bg-[var(--orange)]' : i === 2 ? 'bg-purple-300' : 'bg-[#536078]'}`} style={{width: progress}} /></div></div>)}</div></div></div>
          <div className="mt-6 rounded-xl border border-[var(--line)] bg-[var(--panel)]"><div className="flex flex-col gap-4 border-b border-[var(--line)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold">Prompt Database</div><div className="mono mt-1 text-[10px] text-[var(--muted)]">PUBLIC.PROMPT_LOGS / RECENT RUNS</div></div><div className="relative"><Search className="absolute left-3 top-2.5 text-[var(--muted)]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter logs…" className="rounded-lg border border-[var(--line)] bg-[#0b0e14] py-2 pl-9 pr-3 text-xs outline-none focus:border-[var(--cyan)]" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="mono text-[10px] uppercase tracking-[.14em] text-[var(--muted)]"><tr><th className="px-5 py-3 font-normal">Prompt title</th><th className="px-5 py-3 font-normal">Strategy</th><th className="px-5 py-3 font-normal">Tokens</th><th className="px-5 py-3 font-normal">Created</th><th className="px-5 py-3 font-normal">Status</th></tr></thead><tbody>{filteredLogs.map((log) => <tr key={`${log.title}-${log.time}`} className="border-t border-[var(--line)] transition hover:bg-[#141a25]"><td className="px-5 py-4"><div>{log.title}</div><div className="mt-1 max-w-[420px] truncate text-xs text-[var(--muted)]">{log.prompt}</div></td><td className="px-5 py-4"><span className="rounded border border-[var(--line)] px-2 py-1 text-xs text-[var(--cyan)]">{log.strategy}</span></td><td className="mono px-5 py-4 text-xs text-[var(--muted)]">{log.tokens.toLocaleString()}</td><td className="mono px-5 py-4 text-xs text-[var(--muted)]">{log.time}</td><td className="px-5 py-4"><span className="flex items-center gap-2 text-xs text-[var(--green)]"><span className="size-1.5 rounded-full bg-[var(--green)]" />{log.status}</span></td></tr>)}</tbody></table></div></div>
        </div>
      </section>
    </div>
  </main>
}
